name: visioncut
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15108
title: visioncut
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fa2a1d'
    - '#576b10'
    - '#d7570c'
    - '#932843'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
