name: visioncut
favicon: null
layout_spectrum: 0.24235
typography_spectrum: 0.84779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#939393'
    - '#1c1c1c'
    - '#5b5b5b'
    - '#e9e9e9'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
