name: visioncut
favicon: null
layout_spectrum: 0.74575
typography_spectrum: 0.84779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#64e8f9'
    - '#a8ff8b'
    - '#439ca7'
    - '#fffcff'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
