name: visioncut
favicon: null
layout_spectrum: 0.24527
typography_spectrum: 0.84779
title: Producciones Audiovisuales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120e0d'
    - '#828282'
    - '#d3d8d6'
    - '#664442'
    - '#c4aaa3'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
