name: visioncut
favicon: null
layout_spectrum: 0.50257
typography_spectrum: 0.84372
title: visioncut
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2262ac'
    - '#3aa0fd'
    - '#cdcac7'
    - '#000000'
    - '#59feff'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
